name: New resource
description: Request to add a new resource
title: "Request new resource: "
labels: [resource, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: title
    attributes:
      label: Title
      description: Which title needs to be shown in the selection menu
    validations:
      required: true
  - type: input
    id: endpoint
    attributes:
      label: Endpoint
      description: Endpoint to get a random quote
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author name
      description: What's the name of the author who created the api
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Author website
      description: The authors website or profile page
    validations:
      required: true
  - type: checkboxes
    id: self
    attributes:
      label: Will you create the change?
      options:
        - label: "Yes, I'll create the changes myself and create a pull request for them"
